# Generated by Django 4.1.2 on 2022-11-23 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppUsuario', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
