# Generated by Django 4.1.2 on 2022-11-23 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppUsuario', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
