# Generated by Django 4.1.2 on 2022-11-24 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppUsuario', '0006_alter_avatar_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
